Hybrid offshore wind
quintel/documentation pull request #195
Opened 2024-06-17 08:44 UTC by kndehaan

With this PR the modelling of hybrid offshore wind is added to the ETM. This comes with, among others, the following features:

- Hybrid offshore wind turbine that can generate electricity for HV network or directly for connected offshore electrolyser
- Price-based offshore electrolyser that can receive electricity from hybrid wind turbine or from onshore HV network
- Front-end sliders to set installed (relative) capacities of the components and other relevant specs (e.g. costs, full load hours)
- 3 new front-end outputs: a bar chart, Sankey diagram and table that provide data on capacities and energy flows of hybrid offshore wind

2024-06-17 13:54 UTC, mabijkerk requested changes

2024-06-17 13:54 UTC, mabijkerk commented on docs/main/hybrid-offshore-wind.md
> +</div>
Again, I would use a downloaded chart here rather than a screenshot.

2024-06-17 13:54 UTC, mabijkerk commented on docs/main/hybrid-offshore-wind.md
> +In case of excess electricity production, meaning when the capacity of the electrolyser is fully exploited and either the capacity of the electricity cable is fully exploited or onshore electricity d
I feel like the behaviour of the component is a bit text-heavy in general. Specifically though, I feel that this part could be somewhat clearer. The general behaviour of components should be simple enough. The special case that the user should know is that the electrolyser will run **even when the price > WTP**, before curtailment is used. Maybe we can use a :::caution info box to alert users of this?

2024-06-17 13:55 UTC, mabijkerk commented
Why is the hybrid wind turbine call "Hybrid offshore wind" on the 'main' page, but the "Hybrid offshore hub" on the 'for contributors' page?

2024-06-18 08:23 UTC, kndehaan commented
> Why is the hybrid wind turbine call "Hybrid offshore wind" on the 'main' page, but the "Hybrid offshore hub" on the 'for contributors' page?

The hybrid offshore wind is mainly explaining the hybrid offshore wind components as it currently is. The idea of the hybrid offshore hub title for the respective page is to give it a general 'hub' focus, since this hub can be complemented with e.g. solar, interconnectors, batteries, in the future.

2024-06-24 09:24 UTC, merged